### ISSUE TITLE
Calling mark on line 1015

### ISSUE THREAD

**Issue by vygr** [marcpaq/arpilisp#1]
Hi, nice project. Reminds me somewhat of the Jones Forth but for Lisp. :)

Looking through the source, on line 1015 your calling mark which ends up marking the object in r2. That object has been placed on the stack, so on calling collect garbage it will be marked anyways.

So I think you can remove that call. Very minor issue I know, but proves I'm paying attention. :) or missing something subtle...

Best regards

Chris

**Comment by marcpaq** [comment]
Hi Chris,

Thanks for the compliment and the sharp eye. Yes, I can and did remove that call.

Fixed.

Marc.
