### ISSUE TITLE
Raspberry PI work

### ISSUE THREAD

**Issue by vygr** [marcpaq/arpilisp#4]
Hi Marc, not really an issue but thought you'd like to know. I got my OS ported over onto the Raspberry PI3 and created a Lisp to remove my dependancy on any other compilers/assemblers.

May be of interest to you ? 2 seconds to build from source the entire OS, including the compiler, GUI, and libs etc :)

The Lisp is coded in assembler, but a virtual assembler of my own design, the ARM64 backend is around 350 LOC.

https://github.com/vygr/ChrysaLisp

Best regards

Chris

**Comment by marcpaq** [comment]
Chris, that's pretty slick. What you've done is elegant and impressive.

(Years ago I remember reading about a some research on a statically-typed Lisp with no GC intended for systems programming, but I can't find it on google.)

Thanks for sharing!

Marc.
