### ISSUE TITLE
A macro system in a future?

### ISSUE THREAD

**Issue by maxxcan** [marcpaq/arpilisp#8]
First, thank you for this interpreter. I am a enthusiast of Lisp and thanks to you I can programming in Lisp anywhere. 

It's very interesting have a minimal lisp interpreter like John McCarthy made it in the first moment, but for the extend this language another big improve was the macro system. 

Do yo think implement it in this interpreter? 

Thank you very much.

**Comment by marcpaq** [comment]
I'm happy you like arpilisp. 

I accomplished what I set out to do and I'm happy with the result. 

Of course, you can always implement a macro system yourself. Kent Dybvig and other people have shared excellent knowledge on the subject. 

I hope you have as much fun as I did with your own arpilisp hacking. Let me know how it goes!
